
import { Property } from './types';

export const COLORS = {
  primary: 'indigo-700',
  secondary: 'teal-500',
  accent: 'orange-500',
  bg: 'slate-50',
};

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Spacious 2BHK in Indiranagar',
    type: 'Apartment',
    bhk: 2,
    furnishing: 'Semi Furnished',
    location: 'Indiranagar, Bangalore',
    price: 35000,
    maintenance: 2500,
    deposit: 150000,
    availableFrom: '2023-11-01',
    description: 'A beautiful semi-furnished apartment in the heart of Indiranagar. Walking distance to 100ft Road and Metro station. Modular kitchen and wardrobes included.',
    amenities: ['Power Backup', 'Lift', 'Covered Parking', 'Security', 'Geyser'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1000', 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1000'],
    ownerId: 'owner1',
    rating: 4.8,
    views: 1250,
  },
  {
    id: '2',
    title: 'Co-ed Student PG near North Campus',
    type: 'PG/Hostel',
    furnishing: 'Fully Furnished',
    location: 'GTB Nagar, Delhi',
    price: 12000,
    deposit: 12000,
    availableFrom: '2023-10-15',
    description: 'Perfect for DU students. Includes 3-time home-cooked meals, high-speed WiFi, daily housekeeping, and laundry service. No curfew.',
    amenities: ['WiFi', 'Meals Included', 'Laundry', 'RO Water', 'CCTV', 'AC'],
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?q=80&w=1000', 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1000'],
    ownerId: 'owner2',
    rating: 4.2,
    views: 890,
  },
  {
    id: '3',
    title: 'Luxury 3BHK Sea View Apartment',
    type: 'Apartment',
    bhk: 3,
    furnishing: 'Fully Furnished',
    location: 'Bandra West, Mumbai',
    price: 125000,
    maintenance: 12000,
    deposit: 500000,
    availableFrom: 'Immediately',
    description: 'Premium sea-facing apartment with modern Italian interiors. Society has a clubhouse, gym, and swimming pool. Ideal for expats and families.',
    amenities: ['Sea View', 'Gym', 'Swimming Pool', 'Gated Society', 'Servant Quarter', 'Central AC'],
    images: ['https://images.unsplash.com/photo-1512918760513-95f1929757fc?q=80&w=1000', 'https://images.unsplash.com/photo-1600596542815-2a4d04fb7529?q=80&w=1000'],
    ownerId: 'owner1',
    rating: 4.9,
    views: 3100,
  },
  {
    id: '4',
    title: 'Affordable 1RK Studio',
    type: 'Apartment',
    bhk: 1,
    furnishing: 'Unfurnished',
    location: 'Hinjewadi Phase 1, Pune',
    price: 8500,
    maintenance: 500,
    deposit: 25000,
    availableFrom: '2023-12-01',
    description: 'Compact studio apartment near IT park. Ideal for bachelors working in Hinjewadi. 24/7 water supply and bike parking available.',
    amenities: ['Water Supply', 'Bike Parking', 'CCTV', 'Lift'],
    images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?q=80&w=1000'],
    ownerId: 'owner3',
    rating: 4.0,
    views: 3400,
  },
  {
    id: '5',
    title: 'Premium Men\'s PG in HSR Layout',
    type: 'PG/Hostel',
    furnishing: 'Fully Furnished',
    location: 'HSR Layout Sector 4, Bangalore',
    price: 16000,
    deposit: 16000,
    availableFrom: 'Immediately',
    description: 'Upscale PG for working professionals. Single occupancy rooms with attached washroom. Gym and gaming zone in common area.',
    amenities: ['WiFi', 'Power Backup', 'Housekeeping', 'Gaming Zone', 'Attached Balcony', 'Fridge'],
    images: ['https://images.unsplash.com/photo-1522771753035-1a5b6562f3ba?q=80&w=1000'],
    ownerId: 'owner4',
    rating: 4.6,
    views: 1500,
  },
  {
    id: '6',
    title: 'Indep. House 3BHK - Gated Community',
    type: 'Independent House',
    bhk: 3,
    furnishing: 'Semi Furnished',
    location: 'Gachibowli, Hyderabad',
    price: 45000,
    maintenance: 3000,
    deposit: 100000,
    availableFrom: '2023-11-15',
    description: 'Spacious independent villa in a peaceful gated community. Close to Financial District. Has a private garden and terrace.',
    amenities: ['Private Garden', 'Car Parking', 'Pet Friendly', 'Security', 'Club House'],
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1000', 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1000'],
    ownerId: 'owner5',
    rating: 4.7,
    views: 2200,
  },
  {
    id: '7',
    title: '2BHK near Manyata Tech Park',
    type: 'Apartment',
    bhk: 2,
    furnishing: 'Fully Furnished',
    location: 'Hebbal, Bangalore',
    price: 28000,
    maintenance: 2000,
    deposit: 100000,
    availableFrom: 'Immediately',
    description: 'Fully furnished flat with TV, Sofa, Beds and Washing Machine. 10 mins walk to Manyata. Ideal for techies.',
    amenities: ['Fully Furnished', 'Washing Machine', 'TV', 'Power Backup', 'Gym'],
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1000'],
    ownerId: 'owner6',
    rating: 4.3,
    views: 950,
  },
  {
    id: '8',
    title: 'Single Room for Working Women',
    type: 'Room',
    furnishing: 'Semi Furnished',
    location: 'Koramangala 5th Block, Bangalore',
    price: 14000,
    deposit: 40000,
    availableFrom: '2023-10-20',
    description: 'Single room in a shared 3BHK flat. Kitchen and Hall shared. Safe neighborhood, very close to cafes and parks.',
    amenities: ['Shared Kitchen', 'No Restrictions', 'WiFi', 'Geyser'],
    images: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1000'],
    ownerId: 'owner7',
    rating: 4.5,
    views: 1100,
  },
  {
    id: '9',
    title: 'High-Rise 4BHK Penthouse',
    type: 'Apartment',
    bhk: 4,
    furnishing: 'Fully Furnished',
    location: 'Golf Course Road, Gurgaon',
    price: 180000,
    maintenance: 15000,
    deposit: 600000,
    availableFrom: '2023-12-01',
    description: 'Ultra-luxury penthouse with golf course view. Private elevator access, jacuzzi, and italian marble flooring.',
    amenities: ['Penthouse', 'Golf View', 'Jacuzzi', 'Concierge', 'Valet Parking'],
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1000'],
    ownerId: 'owner8',
    rating: 5.0,
    views: 4500,
  },
  {
    id: '10',
    title: '1BHK in Powai Hiranandani',
    type: 'Apartment',
    bhk: 1,
    furnishing: 'Fully Furnished',
    location: 'Powai, Mumbai',
    price: 45000,
    maintenance: 0,
    deposit: 150000,
    availableFrom: 'Immediately',
    description: 'Compact 1BHK in the prestigious Hiranandani Gardens. Walkable to offices, cafes and Galleria.',
    amenities: ['Park View', 'AC', 'Modular Kitchen', 'Security'],
    images: ['https://images.unsplash.com/photo-1484154218962-a1c002085d2f?q=80&w=1000'],
    ownerId: 'owner9',
    rating: 4.4,
    views: 1800,
  }
];
